# LMGTFY by Nikl



# Options:
#    default, default.yml             This option uses the up to date english language file
#                                     from INSIDE the jar. With this option messages are not configurable!
#
#    lang_en.yml, lang_de.yml,        These are default language files that are in the folder 'LMGTFY\language'.
#    lang_zh-cn.yml                   With these options you can customize messages by simply changing them
#                                     inside the file you chose (then reload the plugin).
#
#    <your_lang_file>.yml             You can create any yml file inside the language folder and fully
#                                     customize all messages :)
#
# If any messages are missing in the used file, they are taken from the default file.
langFile: default

# Enable shortener?
useShortener: true
# List of available shortener ports
#  - International https://is.gd/create.php?format=simple&url=
#  - International https://u.nu/api.php?action=shorturl&format=simple&url=
#  - International http://chilp.it/api.php?url=
#  - International https://is.gd/api.php?longurl=
#  - International https://v.gd/create.php?format=simple&url= (No recommended)
#  - International http://www.jdem.cz/get?url=
#  - Chinese http://suo.im/api.php?url=
#  - Chinese http://api.ft12.com/api.php?url=
#  - Chinese http://api.c7.gg/api.php?url=
#  - Chinese http://api.kks.me/api.php?url=
#  - Chinese http://api.u6.gg/api.php?url=
#  - Chinese http://api.rrd.me/api.php?url=
#  - Chinese http://api.uee.me/api.php?url=
#  - Chinese http://www.hanhanzs.com/api?api=KbToxxJ3kcvG&url=
#  - Default: http://is.gd/create.php?format=simple&url=
#Current port (If the ports above dont work, please change http to https, or change https to http)
Interface: "https://is.gd/create.php?format=simple&url="

# lmgtfy mode
#    Currently supported search engines: google, yahoo, bing and duckduckgo
#    For an up to date list, please refer to the plugins page on Spigot
lmgtfyMode: google

# toggle bStats
#    see: https://bstats.org/plugin/bukkit/LMGTFY
# please let me have my statistics :P
bStats: true
