# --------------------------------------------------------------------------------------#
#                                                                                       #
#                                     LMGTFY config                                     #
#                                                                                       #
# --------------------------------------------------------------------------------------#
# Made by Nikl (https://www.spigotmc.org/resources/authors/205362/)


# Options:
#    default, default.yml             This option uses the up to date english language file
#                                     from INSIDE the jar. With this option messages are not configurable!
#
#    lang_en.yml, lang_de.yml,        These are default language files that are in the folder 'LMGTFY\language'.
#    lang_zh-cn.yml                   With these options you can customize messages by simply changing them
#                                     inside the file you chose (then reload the plugin).
#
#    <your_lang_file>.yml             You can create any yml file inside the language folder and fully
#                                     customize all messages :)
#
# If any messages are missing in the used file, they are taken from the default file.
langFile: default

# this option lets the plugin send a request to a link shortening service.
# Then the shortened link is send instead of the full query link to lmgtfy
#   Please note the rate limits for this service: https://is.gd/usagelimits.php
useShorteningService: true

# An example list of shortening services
# It works with others, too. So if you know a different service, just try it out.
# Note: The service should have TLS active (https, not only http)
#   minecraft does not open http links anymore in click events
#  - International https://chilp.it/api.php?url=
#  - International https://is.gd/api.php?longurl=
#  - International https://v.gd/create.php?format=simple&url= (not recommended)
shortener: "https://is.gd/api.php?longurl="

# lmgtfy mode
#    Currently supported search engines: google, yahoo, bing and duckduckgo
#    For an up to date list, please refer to the plugins page on Spigot
lmgtfyMode: google

# This cooldown does not restrict the creation of the links.
#    It only restricts sending of the link in the chat. (bypass permission 'lmgtfy.bypass')
# To disable cool down simply set it to 0
chatCoolDown: 30

# toggle bStats
#    see: https://bstats.org/plugin/bukkit/LMGTFY
# bStats does not put any stress on your server/network and only sends anonymous data.
# please let me have my statistics :P
bStats: true